[package]
name = "json-joy-buffers"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Binary buffer utilities for json-joy"

[dependencies]

[dev-dependencies]

[features]
default = []
