[package]
name = "json-joy-base64"
version = "0.18.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Base64 encoding/decoding for json-joy"

[dependencies]

[dev-dependencies]
rand = "0.8"

[features]
default = []
